# default_language_version:
#     python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.13.2"
    hooks:
      - id: ruff
  - repo: https://github.com/ambv/black
    rev: 25.9.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
  # - repo: https://github.com/astral-sh/ty
  #   rev: "0.0.21"
  #   hooks:
  #     - id: ty
  #       args: [check, src, tests]
