from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent
ROOT_DIR = DOCS_DIR.parent
SOURCE_PATH = ROOT_DIR / "CONTRIBUTING.md"
TARGET_PATH = DOCS_DIR / "package_info" / "contributing.md"
GENERATED_HEADER = (
    "<!-- Generated from ../../CONTRIBUTING.md. Do not edit this file directly. -->\n\n"
)
CODE_OF_CONDUCT_LINK = "https://github.com/mggg/VoteKit/blob/main/CODE_OF_CONDUCT.md"


def sync_contributing_doc() -> None:
    text = SOURCE_PATH.read_text()
    text = text.replace(
        "[CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md)",
        f"[CODE_OF_CONDUCT.md]({CODE_OF_CONDUCT_LINK})",
    )

    generated_text = GENERATED_HEADER + text

    TARGET_PATH.parent.mkdir(parents=True, exist_ok=True)
    if TARGET_PATH.exists() and TARGET_PATH.read_text() == generated_text:
        return

    TARGET_PATH.write_text(generated_text)


if __name__ == "__main__":
    sync_contributing_doc()
